### ISSUE TITLE
Execution errors

### ISSUE THREAD

**Issue by irons** [sshaw/itunes_store_transporter#8]
I was curious about this tool's ability to make sense of iTMSTransporter's error messages, but I haven't been able to get it off the ground. I'm using ruby 2.1.5p273, itunes_store_transporter 0.1.1, Xcode 6.1.1, on OS X 10.9.5. The interactive command always fails, in a couple of different ways. 

First, if I specify my credentials in the command, itms always rejects the package's name as invalid:

    itms verify --username me@mydomain.com --password "blahblah" --package package.itmsp
    Running command 'verify'
    
    option invalid: package; dir name must match '(?-mix:\.itmsp\z)'

I banged my head against this for a while, then tried storing the username and password in `~/.itms`. That led to a different error:

    itms verify --package package.itmsp
	Running command 'verify'

	1 error(s)
	-------------------------
	1. Please specify a value for required option: f

This looks to me like iTMSTransporter isn't being told the path of the package, but if I leave off the --package argument, itms barks at me: `option required: 'package'`.

FWIW, if I run iTMSTransporter in verify mode on the same package I'm passing to itms, I get the expected russian novel of status output.

**Comment by sshaw** [comment]
Hi

> itms verify --username me@mydomain.com --password "blahblah" --package package.itmsp
> ...
> option invalid: package; dir name must match '(?-mix:\.itmsp\z)'

The options must have an `=` at the end, so `--password=blahblah`. See: https://github.com/sshaw/itunes_store_transporter#using-itms. But this should be changed as it's not necessarily intuitive. 

Can you please try it again with the `=`? I will give it a try on my end too. 

Thanks

**Comment by sshaw** [comment]
Okay, I've confirmed this is a bug. Will have a fix shortly.

**Comment by sshaw** [comment]
Wait, no it's not... The problem is that the `itms` command is supposed to match the equivalent call in the library. So [here's verify's docs](http://ruby-doc.org/gems/docs/i/itunes_store_transporter-0.1.1/ITunes/Store/Transporter/ITMSTransporter.html#method-i-verify), the call is: `verify(package, options = {})`. Here, package is provided as a positional argument, not a named option. So your call should be:

```
itms verify --username=me@mydomain.com --password="blahblah" package.itmsp
```
As you can see, after not using this command for a while even I was a tad confused. I created #9 but if you have any other ideas on how to improve the docs (I do mention the above, should probably be clearer) or the command please let me know.


> I was curious about this tool's ability to make sense of iTMSTransporter's error messages

Should do a good job. If you wouldn't mind checking out [this branch]( https://github.com/sshaw/itunes_store_transporter/tree/output_parser_main_only) and giving me some feedback that would be great. It contains a small fix that ignores errors from other classes like Aspera.

> ... expected russian novel of status output

Now that's funny...

**Comment by sshaw** [comment]
I updated to docs to better describe `itms`'s options.
